### ISSUE TITLE
Update PowerCLI-Example-Scripts

### ISSUE THREAD

**Issue by DisasteR** [vmware/powerclicore#66]
### Is your feature request related to a problem? Please describe.

Integrated PowerCLI-Example-Scripts modules are from 2019 and contain old scripts versions.

### Describe the solution you'd like

update to latest version of PowerCLI-Example-Scripts.
https://github.com/vmware/PowerCLI-Example-Scripts/archive/c74ae8cd7d65ca95a8a2cadc68afddc1455fc838.zip

**Comment by tenthirtyam** [comment]
Hi @DisasteR and @dmilov! 👋 

There are two better ways of making this change.

1. Change the URL from a specific archive to the one generated directly from the `master` branch.

   Change this:
   
   https://github.com/vmware/powerclicore/blob/835167f44b6dc4bde8e479beceabaf480d58bb9a/Dockerfile#L22

   To this: 
   
    ```bash
    curl -o ./PowerCLI-Example-Scripts.zip -J -L https://github.com/vmware/PowerCLI-Example-Scripts/archive/refs/heads/master.zip && \
   ```

2. A **better** option is to simply clone the repository using git since it's already installed by the `tdnf` commands:

   Change  this:

   https://github.com/vmware/powerclicore/blob/835167f44b6dc4bde8e479beceabaf480d58bb9a/Dockerfile#L22-L26

   To this:

    ```bash
    git clone https://github.com/vmware/PowerCLI-Example-Scripts.git community-examples && \
    mv ./community-examples/Modules/* /usr/lib/powershell/Modules/ && \
    ```

   This remove `unzip` from:

   https://github.com/vmware/powerclicore/blob/835167f44b6dc4bde8e479beceabaf480d58bb9a/Dockerfile#L12

   and....

    https://github.com/vmware/powerclicore/blob/835167f44b6dc4bde8e479beceabaf480d58bb9a/Dockerfile#L29

Hope this helps. Happy to put in a PR, if you like.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
